name: Lockbud CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: sigmaprime/lockbud:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: apt update && apt install -y cmake
      - name: Generate code coverage
        run: |
          cargo lockbud -k deadlock -b -l tokio_util
